### PR TITLE
Rename Recommendation API to Personalization API

### PR DESCRIPTION
**Pull request by redox**
With the release of Algolia Recommend, we need to rename our legacy "recommendation_client" to "personalization_client".

This PR also documents the GET/DELETE of user profiles.

We need them to use `personalization.$ region.algolia.com`

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]

**Comment by redox** [comment]
Thank you @Haroenv ! Do we have a smart way to create GH issues for all API clients in order for this update to be added to their backlog?

**Review by DevinCodes — APPROVED** [review]

**Comment by DevinCodes** [comment]
I believe we can use [polyglot](https://github.com/algolia/polyglot) for that. @Haroenv do you have that set up on your machine?

**Review by VladislavFitz — APPROVED** [review]

**Comment by VladislavFitz** [comment]
@DevinCodes I have it on my machine. I'll create an issue in our API clients internal repo.

**Comment by VladislavFitz** [comment]
[Done!](https://github.com/algolia/algoliasearch-client-specs-internal/issues/165)

**Comment by redox** [comment]
Thank you @VladislavFitz

**Pull request merged**
